export const GET_CAMPANAS_TO_LLAMADAS = "GET_CAMPANAS_TO_LLAMADAS";
export const GET_CAMPANA_REGISTRO_TO_LLAMADAS = "GET_CAMPANA_REGISTRO_TO_LLAMADAS";
export const GENERATE_CALL = "GENERATE_CALL";
export const RESET_LLAMADAPREV_STATE="RESET_LLAMADAPREV_STATE";
export const SHOW_ESTADO_LLAMADA = "SHOW_ESTADO_LLAMADA";