export { default as Login } from './Login/Login';
export { default as Prueba } from './Prueba';
export { default as Dashboard } from './Dashborad/Dashboard';
export { default as DashboardWholePage } from './DashboardWholePage/DashboardWholePage';
export { default as PageNotFound } from './PageNotFound/PageNotFound';
export { default as Empresa } from './Empresa/Empresa';
export { default as Sucursal } from './Sucursal/Sucursal';
export { default as Departamento } from './Departamento/Departamento';
export { default as EmpresaEdit } from './Empresa/EmpresaEdit';
export { default as SucursalEdit } from './Sucursal/SucursalEdit';
export { default as DepartamentoEdit } from './Departamento/DepartamentoEdit';
export { default as MantPermisos } from './MantPermisos/MantPermisos';
export { default as MenuPermiso } from './MenuPermiso/MenuPermiso';
export { default as Usuario } from './Usuario/Usuario';
export { default as UsuarioEdit} from './Usuario/UsuarioEdit';
export { default as Extension } from './Extension/Extension';
export { default as ExtensionEdit} from './Extension/ExtensionEdit';
export { default as MusicaEnEsperaV2 } from './MusicaEnEspera/MusicaEnEsperav2';
export { default as MusicaEnEsperaEdit} from "./MusicaEnEspera/MusicaEnEsperaEdit";
export { default as MantEstadoAgente } from './MantEstadoAgente/MantEstadoAgente';
export { default as MantEstadoAgenteEdit } from './MantEstadoAgente/MantEstadoAgenteEdit';
export { default as ReporteRegistroLlamadas } from "../pages/Reporte/LLamadas/RegistroLlamadas";
export { default as Grabaciones} from "./Grabaciones/Grabaciones";
export { default as GrabacionesEdit} from "./Grabaciones/GrabacionesEdit";
export { default as Colas} from "./Colas/Colas";
export { default as ColasEdit} from "./Colas/ColasEdit";
export { default as ColasRules} from "./ColasRules/ColasRules";
export { default as ColasRulesEdit} from "./ColasRules/ColasRulesEdit";
export { default as ColasRulesEditConf} from "./ColasRules/ColasRulesEditConf";
export { default as ColasMiembrosEditar} from "./Colas/ColasMiembrosEditar";
export { default as ColasMiembrosEditarDinamicos} from "./Colas/ColasMiembrosEditarDinamicos";
export { default as ColasMiembrosInsertPage} from "./Colas/ColasMiembrosInsertPage";
export { default as ColasMiembrosInsertPageDInamicos} from "./Colas/ColasMiembrosInsertPageDInamicos";
export { default as DetalleColas} from "./Reporte/DetalleColas/DetalleColas";
export { default as ResumenColas} from "./Reporte/ResumenColas/ResumenColas";
export { default as ActividadAgente} from "./Reporte/ActividadAgente/ActividadAgente";
export { default as ResumenAgentesColas} from "./Reporte/ResumenAgentesColas/ResumenAgentesColas";
export { default as LlamadasAbandonadas} from "./Reporte/LlamadaAbandonadas/LlamadasAbandonadas";
export { default as Contactos} from "./Contactos/Contactos";
export { default as ContactosEdit} from "./Contactos/ContactosEdit";
export { default as ResumenAgentes} from "./Reporte/ResumenAgentes/ResumenAgentes";
export { default as Campanas} from "./Campanas/Campanas";
export { default as CampanasEdit} from "./Campanas/CampanasEdit";
export { default as CampanasRegistros} from "./CampanasRegistros/CampanasRegistros";
export { default as CampanasRegistrosEdit} from "./CampanasRegistros/CampanasRegistrosEdit";